# Generated by Django 2.2.17 on 2020-12-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='pay_stauts',
            new_name='pay_status',
        ),
    ]
